spring.application.name=Security Demo

# Spring security changing default password
spring.security.user.name=user
spring.security.user.password=demo@123


spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb

spring.app.jwtSecret=yilOYHDQy1nUmrj2gy7V0JKIoCARrJqvQXbp6D9BGjB
spring.app.jwtExpirationMs=300000

logging.level.root=DEBUG
logging.level.com.example.securitydemo=DEBUG
logging.level.org.springframework.security=DEBUG